//
//todo 前置条件
//
//# 插件1：生成 所有message对应的Go结构体代码（基础数据结构）
//go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//
//# 插件2：生成 gRPC的服务端骨架 + 客户端Stub桩代码（核心grpc调用逻辑）
//go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: book_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookServer_AddBook_FullMethodName        = "/book.BookServer/AddBook"
	BookServer_GetBookByID_FullMethodName    = "/book.BookServer/GetBookByID"
	BookServer_DeleteBookByID_FullMethodName = "/book.BookServer/DeleteBookByID"
	BookServer_FindBooks_FullMethodName      = "/book.BookServer/FindBooks"
	BookServer_UpdateBook_FullMethodName     = "/book.BookServer/UpdateBook"
)

// BookServerClient is the client API for BookServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type BookServerClient interface {
	AddBook(ctx context.Context, in *AddBookReq, opts ...grpc.CallOption) (*CommonResp, error)
	GetBookByID(ctx context.Context, in *BookIDReq, opts ...grpc.CallOption) (*GetBookByIDResp, error)
	DeleteBookByID(ctx context.Context, in *BookIDReq, opts ...grpc.CallOption) (*CommonResp, error)
	FindBooks(ctx context.Context, in *FindBooksResp, opts ...grpc.CallOption) (*FindBooksResp, error)
	UpdateBook(ctx context.Context, in *UpDateBookReq, opts ...grpc.CallOption) (*CommonResp, error)
}

type bookServerClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServerClient(cc grpc.ClientConnInterface) BookServerClient {
	return &bookServerClient{cc}
}

func (c *bookServerClient) AddBook(ctx context.Context, in *AddBookReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, BookServer_AddBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerClient) GetBookByID(ctx context.Context, in *BookIDReq, opts ...grpc.CallOption) (*GetBookByIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookByIDResp)
	err := c.cc.Invoke(ctx, BookServer_GetBookByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerClient) DeleteBookByID(ctx context.Context, in *BookIDReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, BookServer_DeleteBookByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerClient) FindBooks(ctx context.Context, in *FindBooksResp, opts ...grpc.CallOption) (*FindBooksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindBooksResp)
	err := c.cc.Invoke(ctx, BookServer_FindBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServerClient) UpdateBook(ctx context.Context, in *UpDateBookReq, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, BookServer_UpdateBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServerServer is the server API for BookServer service.
// All implementations must embed UnimplementedBookServerServer
// for forward compatibility.
//
// 定义服务
type BookServerServer interface {
	AddBook(context.Context, *AddBookReq) (*CommonResp, error)
	GetBookByID(context.Context, *BookIDReq) (*GetBookByIDResp, error)
	DeleteBookByID(context.Context, *BookIDReq) (*CommonResp, error)
	FindBooks(context.Context, *FindBooksResp) (*FindBooksResp, error)
	UpdateBook(context.Context, *UpDateBookReq) (*CommonResp, error)
	mustEmbedUnimplementedBookServerServer()
}

// UnimplementedBookServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookServerServer struct{}

func (UnimplementedBookServerServer) AddBook(context.Context, *AddBookReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBook not implemented")
}
func (UnimplementedBookServerServer) GetBookByID(context.Context, *BookIDReq) (*GetBookByIDResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookByID not implemented")
}
func (UnimplementedBookServerServer) DeleteBookByID(context.Context, *BookIDReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBookByID not implemented")
}
func (UnimplementedBookServerServer) FindBooks(context.Context, *FindBooksResp) (*FindBooksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindBooks not implemented")
}
func (UnimplementedBookServerServer) UpdateBook(context.Context, *UpDateBookReq) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookServerServer) mustEmbedUnimplementedBookServerServer() {}
func (UnimplementedBookServerServer) testEmbeddedByValue()                    {}

// UnsafeBookServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServerServer will
// result in compilation errors.
type UnsafeBookServerServer interface {
	mustEmbedUnimplementedBookServerServer()
}

func RegisterBookServerServer(s grpc.ServiceRegistrar, srv BookServerServer) {
	// If the following call panics, it indicates UnimplementedBookServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookServer_ServiceDesc, srv)
}

func _BookServer_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServerServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServer_AddBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServerServer).AddBook(ctx, req.(*AddBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookServer_GetBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServerServer).GetBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServer_GetBookByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServerServer).GetBookByID(ctx, req.(*BookIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookServer_DeleteBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServerServer).DeleteBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServer_DeleteBookByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServerServer).DeleteBookByID(ctx, req.(*BookIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookServer_FindBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBooksResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServerServer).FindBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServer_FindBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServerServer).FindBooks(ctx, req.(*FindBooksResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookServer_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpDateBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServerServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServer_UpdateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServerServer).UpdateBook(ctx, req.(*UpDateBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BookServer_ServiceDesc is the grpc.ServiceDesc for BookServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookServer",
	HandlerType: (*BookServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookServer_AddBook_Handler,
		},
		{
			MethodName: "GetBookByID",
			Handler:    _BookServer_GetBookByID_Handler,
		},
		{
			MethodName: "DeleteBookByID",
			Handler:    _BookServer_DeleteBookByID_Handler,
		},
		{
			MethodName: "FindBooks",
			Handler:    _BookServer_FindBooks_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookServer_UpdateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book_server.proto",
}
