//
//todo 前置条件
//
//# 插件1：生成 所有message对应的Go结构体代码（基础数据结构）
//go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//
//# 插件2：生成 gRPC的服务端骨架 + 客户端Stub桩代码（核心grpc调用逻辑）
//go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: book_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义结构体
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookName      string                 `protobuf:"bytes,2,opt,name=bookName,proto3" json:"bookName,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Book) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 请求体
type AddBookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookName      string                 `protobuf:"bytes,1,opt,name=bookName,proto3" json:"bookName,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookReq) Reset() {
	*x = AddBookReq{}
	mi := &file_book_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookReq) ProtoMessage() {}

func (x *AddBookReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookReq.ProtoReflect.Descriptor instead.
func (*AddBookReq) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{1}
}

func (x *AddBookReq) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *AddBookReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AddBookReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddBookReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AddBookReq) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type BookIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookIDReq) Reset() {
	*x = BookIDReq{}
	mi := &file_book_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookIDReq) ProtoMessage() {}

func (x *BookIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookIDReq.ProtoReflect.Descriptor instead.
func (*BookIDReq) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{2}
}

func (x *BookIDReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpDateBookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookName      string                 `protobuf:"bytes,2,opt,name=bookName,proto3" json:"bookName,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpDateBookReq) Reset() {
	*x = UpDateBookReq{}
	mi := &file_book_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpDateBookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpDateBookReq) ProtoMessage() {}

func (x *UpDateBookReq) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpDateBookReq.ProtoReflect.Descriptor instead.
func (*UpDateBookReq) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{3}
}

func (x *UpDateBookReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpDateBookReq) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *UpDateBookReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpDateBookReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpDateBookReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpDateBookReq) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 响应体
type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_book_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{4}
}

func (x *CommonResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetBookByIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Book          *Book                  `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookByIDResp) Reset() {
	*x = GetBookByIDResp{}
	mi := &file_book_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookByIDResp) ProtoMessage() {}

func (x *GetBookByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookByIDResp.ProtoReflect.Descriptor instead.
func (*GetBookByIDResp) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookByIDResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBookByIDResp) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *GetBookByIDResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type FindBooksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Book          []*Book                `protobuf:"bytes,2,rep,name=book,proto3" json:"book,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindBooksResp) Reset() {
	*x = FindBooksResp{}
	mi := &file_book_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBooksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBooksResp) ProtoMessage() {}

func (x *FindBooksResp) ProtoReflect() protoreflect.Message {
	mi := &file_book_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBooksResp.ProtoReflect.Descriptor instead.
func (*FindBooksResp) Descriptor() ([]byte, []int) {
	return file_book_server_proto_rawDescGZIP(), []int{6}
}

func (x *FindBooksResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindBooksResp) GetBook() []*Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *FindBooksResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_book_server_proto protoreflect.FileDescriptor

const file_book_server_proto_rawDesc = "" +
	"\n" +
	"\x11book_server.proto\x12\x04book\"\x8e\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bbookName\x18\x02 \x01(\tR\bbookName\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\"\x84\x01\n" +
	"\n" +
	"AddBookReq\x12\x1a\n" +
	"\bbookName\x18\x01 \x01(\tR\bbookName\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"\x1b\n" +
	"\tBookIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x97\x01\n" +
	"\rUpDateBookReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bbookName\x18\x02 \x01(\tR\bbookName\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\"L\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"_\n" +
	"\x0fGetBookByIDResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\x04book\x18\x02 \x01(\v2\n" +
	".book.BookR\x04book\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"]\n" +
	"\rFindBooksResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\x04book\x18\x02 \x03(\v2\n" +
	".book.BookR\x04book\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code2\x93\x02\n" +
	"\n" +
	"BookServer\x12-\n" +
	"\aAddBook\x12\x10.book.AddBookReq\x1a\x10.book.CommonResp\x125\n" +
	"\vGetBookByID\x12\x0f.book.BookIDReq\x1a\x15.book.GetBookByIDResp\x123\n" +
	"\x0eDeleteBookByID\x12\x0f.book.BookIDReq\x1a\x10.book.CommonResp\x125\n" +
	"\tFindBooks\x12\x13.book.FindBooksResp\x1a\x13.book.FindBooksResp\x123\n" +
	"\n" +
	"UpdateBook\x12\x13.book.UpDateBookReq\x1a\x10.book.CommonRespB\tZ\a./pb;pbb\x06proto3"

var (
	file_book_server_proto_rawDescOnce sync.Once
	file_book_server_proto_rawDescData []byte
)

func file_book_server_proto_rawDescGZIP() []byte {
	file_book_server_proto_rawDescOnce.Do(func() {
		file_book_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_server_proto_rawDesc), len(file_book_server_proto_rawDesc)))
	})
	return file_book_server_proto_rawDescData
}

var file_book_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_book_server_proto_goTypes = []any{
	(*Book)(nil),            // 0: book.Book
	(*AddBookReq)(nil),      // 1: book.AddBookReq
	(*BookIDReq)(nil),       // 2: book.BookIDReq
	(*UpDateBookReq)(nil),   // 3: book.UpDateBookReq
	(*CommonResp)(nil),      // 4: book.CommonResp
	(*GetBookByIDResp)(nil), // 5: book.GetBookByIDResp
	(*FindBooksResp)(nil),   // 6: book.FindBooksResp
}
var file_book_server_proto_depIdxs = []int32{
	0, // 0: book.GetBookByIDResp.book:type_name -> book.Book
	0, // 1: book.FindBooksResp.book:type_name -> book.Book
	1, // 2: book.BookServer.AddBook:input_type -> book.AddBookReq
	2, // 3: book.BookServer.GetBookByID:input_type -> book.BookIDReq
	2, // 4: book.BookServer.DeleteBookByID:input_type -> book.BookIDReq
	6, // 5: book.BookServer.FindBooks:input_type -> book.FindBooksResp
	3, // 6: book.BookServer.UpdateBook:input_type -> book.UpDateBookReq
	4, // 7: book.BookServer.AddBook:output_type -> book.CommonResp
	5, // 8: book.BookServer.GetBookByID:output_type -> book.GetBookByIDResp
	4, // 9: book.BookServer.DeleteBookByID:output_type -> book.CommonResp
	6, // 10: book.BookServer.FindBooks:output_type -> book.FindBooksResp
	4, // 11: book.BookServer.UpdateBook:output_type -> book.CommonResp
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_book_server_proto_init() }
func file_book_server_proto_init() {
	if File_book_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_server_proto_rawDesc), len(file_book_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_server_proto_goTypes,
		DependencyIndexes: file_book_server_proto_depIdxs,
		MessageInfos:      file_book_server_proto_msgTypes,
	}.Build()
	File_book_server_proto = out.File
	file_book_server_proto_goTypes = nil
	file_book_server_proto_depIdxs = nil
}
