# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0bgrpc_task01\"x\n\x10UserRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x0f\n\x07hobbies\x18\x06 \x03(\tJ\x04\x08\x07\x10\x08\"9\n\x18UserRegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"3\n\x10UserLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x11UserLoginResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"!\n\x10UserQueryRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"2\n\x11UserQueryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"@\n\x11UserUpdateRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0f\n\x07hobbies\x18\x04 \x03(\t\"3\n\x12UserUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32\xba\x02\n\x0bUserService\x12P\n\x08Register\x12\x1d.grpc_task01.UserRegistration\x1a%.grpc_task01.UserRegistrationResponse\x12\x46\n\x05Login\x12\x1d.grpc_task01.UserLoginRequest\x1a\x1e.grpc_task01.UserLoginResponse\x12\x46\n\x05Query\x12\x1d.grpc_task01.UserQueryRequest\x1a\x1e.grpc_task01.UserQueryResponse\x12I\n\x06Update\x12\x1e.grpc_task01.UserUpdateRequest\x1a\x1f.grpc_task01.UserUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREGISTRATION']._serialized_start=27
  _globals['_USERREGISTRATION']._serialized_end=147
  _globals['_USERREGISTRATIONRESPONSE']._serialized_start=149
  _globals['_USERREGISTRATIONRESPONSE']._serialized_end=206
  _globals['_USERLOGINREQUEST']._serialized_start=208
  _globals['_USERLOGINREQUEST']._serialized_end=259
  _globals['_USERLOGINRESPONSE']._serialized_start=261
  _globals['_USERLOGINRESPONSE']._serialized_end=311
  _globals['_USERQUERYREQUEST']._serialized_start=313
  _globals['_USERQUERYREQUEST']._serialized_end=346
  _globals['_USERQUERYRESPONSE']._serialized_start=348
  _globals['_USERQUERYRESPONSE']._serialized_end=398
  _globals['_USERUPDATEREQUEST']._serialized_start=400
  _globals['_USERUPDATEREQUEST']._serialized_end=464
  _globals['_USERUPDATERESPONSE']._serialized_start=466
  _globals['_USERUPDATERESPONSE']._serialized_end=517
  _globals['_USERSERVICE']._serialized_start=520
  _globals['_USERSERVICE']._serialized_end=834
# @@protoc_insertion_point(module_scope)
