// 指定当前protobuf文件采用的语法版本为 proto3 版本
// proto3 是目前主流、推荐的版本，兼容性更强，语法更简洁，支持Go/Python/Java等所有grpc主流开发语言

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user.proto

// ========== protobuf 自身的包声明 ==========
// 作用：为当前.proto文件内定义的所有service、message指定【protobuf层面的命名空间】
// 核心：防止多个不同的.proto文件中，出现同名的服务/消息结构体，造成命名冲突

package grpc_task01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户注册请求
type UserRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 姓名,编号1
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码,编号2
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`          // 年龄,编号3
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱,编号4
	Hobbies       []string               `protobuf:"bytes,6,rep,name=hobbies,proto3" json:"hobbies,omitempty"`   // 爱好,编号6  --> repeated表示列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistration) Reset() {
	*x = UserRegistration{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistration) ProtoMessage() {}

func (x *UserRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistration.ProtoReflect.Descriptor instead.
func (*UserRegistration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegistration) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegistration) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserRegistration) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegistration) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

// 用户注册响应
type UserRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 响应消息,编号1
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 错误码,编号2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationResponse) Reset() {
	*x = UserRegistrationResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationResponse) ProtoMessage() {}

func (x *UserRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationResponse.ProtoReflect.Descriptor instead.
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserRegistrationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 用户登录请求
type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱,编号1
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码,编号2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户登录响应
type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 响应消息,编号1
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 错误码,编号2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 用户查询请求
type UserQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // 邮箱,编号1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryRequest) Reset() {
	*x = UserQueryRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryRequest) ProtoMessage() {}

func (x *UserQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryRequest.ProtoReflect.Descriptor instead.
func (*UserQueryRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserQueryRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 用户查询响应
type UserQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 响应消息,编号1
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 错误码,编号2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryResponse) Reset() {
	*x = UserQueryResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResponse) ProtoMessage() {}

func (x *UserQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResponse.ProtoReflect.Descriptor instead.
func (*UserQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserQueryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 用户更新请求
type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`     // 邮箱,编号1
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`        // 年龄,编号2
	Hobbies       []string               `protobuf:"bytes,3,rep,name=hobbies,proto3" json:"hobbies,omitempty"` // 爱好,编号3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserUpdateRequest) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

// 用户更新响应
type UserUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 响应消息,编号1
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 错误码,编号2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateResponse) Reset() {
	*x = UserUpdateResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateResponse) ProtoMessage() {}

func (x *UserUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserUpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\vgrpc_task01\"\x8a\x01\n" +
	"\x10UserRegistration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\ahobbies\x18\x06 \x03(\tR\ahobbiesJ\x04\b\x05\x10\x06\"H\n" +
	"\x18UserRegistrationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"D\n" +
	"\x10UserLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x11UserLoginResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"(\n" +
	"\x10UserQueryRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"A\n" +
	"\x11UserQueryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"U\n" +
	"\x11UserUpdateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x18\n" +
	"\ahobbies\x18\x03 \x03(\tR\ahobbies\"B\n" +
	"\x12UserUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xba\x02\n" +
	"\vUserService\x12P\n" +
	"\bRegister\x12\x1d.grpc_task01.UserRegistration\x1a%.grpc_task01.UserRegistrationResponse\x12F\n" +
	"\x05Login\x12\x1d.grpc_task01.UserLoginRequest\x1a\x1e.grpc_task01.UserLoginResponse\x12F\n" +
	"\x05Query\x12\x1d.grpc_task01.UserQueryRequest\x1a\x1e.grpc_task01.UserQueryResponse\x12I\n" +
	"\x06Update\x12\x1e.grpc_task01.UserUpdateRequest\x1a\x1f.grpc_task01.UserUpdateResponseB\x10Z\x0e./;grpc_task01b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*UserRegistration)(nil),         // 0: grpc_task01.UserRegistration
	(*UserRegistrationResponse)(nil), // 1: grpc_task01.UserRegistrationResponse
	(*UserLoginRequest)(nil),         // 2: grpc_task01.UserLoginRequest
	(*UserLoginResponse)(nil),        // 3: grpc_task01.UserLoginResponse
	(*UserQueryRequest)(nil),         // 4: grpc_task01.UserQueryRequest
	(*UserQueryResponse)(nil),        // 5: grpc_task01.UserQueryResponse
	(*UserUpdateRequest)(nil),        // 6: grpc_task01.UserUpdateRequest
	(*UserUpdateResponse)(nil),       // 7: grpc_task01.UserUpdateResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: grpc_task01.UserService.Register:input_type -> grpc_task01.UserRegistration
	2, // 1: grpc_task01.UserService.Login:input_type -> grpc_task01.UserLoginRequest
	4, // 2: grpc_task01.UserService.Query:input_type -> grpc_task01.UserQueryRequest
	6, // 3: grpc_task01.UserService.Update:input_type -> grpc_task01.UserUpdateRequest
	1, // 4: grpc_task01.UserService.Register:output_type -> grpc_task01.UserRegistrationResponse
	3, // 5: grpc_task01.UserService.Login:output_type -> grpc_task01.UserLoginResponse
	5, // 6: grpc_task01.UserService.Query:output_type -> grpc_task01.UserQueryResponse
	7, // 7: grpc_task01.UserService.Update:output_type -> grpc_task01.UserUpdateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
